/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author AMRI
 */
public class FormUpdateStatusKesehatan extends javax.swing.JFrame {
koneksi kon;
    /**
     * Creates new form FormUpdateStatusKesehatan
     */
    public FormUpdateStatusKesehatan() {
        kon = new koneksi();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1status = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jRadioButtonUpdateOTG = new javax.swing.JRadioButton();
        jRadioButtonUpdatePositif = new javax.swing.JRadioButton();
        jRadioButtonUpdateSuspect = new javax.swing.JRadioButton();
        jRadioButtonUpdatePDP = new javax.swing.JRadioButton();
        jRadioButtonUpdateODP = new javax.swing.JRadioButton();
        jLabelBack = new javax.swing.JLabel();
        jLabelUpdateStatus = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNamaIDPasien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTindakanPerawatan = new javax.swing.JTextField();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jLabel2.setText("Status Kesehatan       :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jLabel3.setText("ID Pasien                      :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        getContentPane().add(jTextFieldNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 280, 30));

        buttonGroup1status.add(jRadioButtonUpdateOTG);
        jRadioButtonUpdateOTG.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jRadioButtonUpdateOTG.setText("Orang Tanpa Gejala");
        getContentPane().add(jRadioButtonUpdateOTG, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, -1));

        buttonGroup1status.add(jRadioButtonUpdatePositif);
        jRadioButtonUpdatePositif.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jRadioButtonUpdatePositif.setText("Positif");
        getContentPane().add(jRadioButtonUpdatePositif, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        buttonGroup1status.add(jRadioButtonUpdateSuspect);
        jRadioButtonUpdateSuspect.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jRadioButtonUpdateSuspect.setText("Suspect");
        getContentPane().add(jRadioButtonUpdateSuspect, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        buttonGroup1status.add(jRadioButtonUpdatePDP);
        jRadioButtonUpdatePDP.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jRadioButtonUpdatePDP.setText("Pasien Dalam Pemantauan");
        getContentPane().add(jRadioButtonUpdatePDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        buttonGroup1status.add(jRadioButtonUpdateODP);
        jRadioButtonUpdateODP.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jRadioButtonUpdateODP.setText("Orang Dalam Pemantauan");
        getContentPane().add(jRadioButtonUpdateODP, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        jLabelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/button_back(1).png"))); // NOI18N
        jLabelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBackMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 170, 50));

        jLabelUpdateStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/updatestatus(1).png"))); // NOI18N
        jLabelUpdateStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUpdateStatusMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelUpdateStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 170, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/online-cloud-medical-health.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 160, 100));

        jLabel6.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jLabel6.setText("Nama                             :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));
        getContentPane().add(jTextFieldNamaIDPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 280, 30));

        jLabel4.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jLabel4.setText("Tindakan Perawatan :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 130, -1));
        getContentPane().add(jTextFieldTindakanPerawatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 280, 30));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/FormUpdateStatusKesehatan.PNG"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelUpdateStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUpdateStatusMouseClicked
        // TODO add your handling code here:
         String nama;
         int id;
        String status_positif ="positif";
        String status_odp ="Orang Dalam Pemantauan";
        String status_pdp ="Pasien Dalam Pemantauan";
        String status_otg ="Orang Tanpa Gejala";
        String status_suspect ="Suspect";
        String tindakan;
        id = Integer.parseInt(jTextFieldNamaIDPasien.getText());
        nama = jTextFieldNama.getText();
        tindakan = jTextFieldTindakanPerawatan.getText();
       
        try{
        if(jRadioButtonUpdatePositif.isSelected()){
            String update1 = "update tb_pasien set status ='"+status_positif+"',tindakan ='"+tindakan+"' where nama ='"+nama+"'";
            Statement st = kon.con.createStatement();
            st.executeUpdate(update1);
            JOptionPane.showMessageDialog(this, "Data pasien dengan nama "+nama+" dan id pasien "+id+" Telah Terupdate");
            this.setVisible(false);
        }
        else if(jRadioButtonUpdateSuspect.isSelected()){
            String update2 = "update tb_pasien set status ='"+status_suspect+"',tindakan ='"+tindakan+"'where nama ='"+nama+"'";
            Statement st = kon.con.createStatement();
            st.executeUpdate(update2);
            JOptionPane.showMessageDialog(this, "Data pasien dengan nama "+nama+" dan id pasien "+id+" Telah Terupdate");
            this.setVisible(false);
        }
        else if(jRadioButtonUpdatePDP.isSelected()){
            String update3 = "update tb_pasien set status ='"+status_pdp+"', tindakan ='"+tindakan+"'where nama ='"+nama+"'";
            Statement st = kon.con.createStatement();
            st.executeUpdate(update3);
            JOptionPane.showMessageDialog(this, "Data pasien dengan nama "+nama+" dan id pasien "+id+" Telah Terupdate");
            this.setVisible(false);
        }
        else if(jRadioButtonUpdateODP.isSelected()){
            String update4 = "update tb_pasien set status ='"+status_odp+"',tindakan ='"+tindakan+"'where nama ='"+nama+"'";
            Statement st = kon.con.createStatement();
            st.executeUpdate(update4);
            JOptionPane.showMessageDialog(this, "Data pasien dengan nama "+nama+" dan id pasien "+id+" Telah Terupdate");
            this.setVisible(false);
        }
         else if(jRadioButtonUpdateOTG.isSelected()){
            String update5 = "update tb_pasien set status ='"+status_otg+"', tindakan ='"+tindakan+"'where nama ='"+nama+"'";
            Statement st = kon.con.createStatement();
            st.executeUpdate(update5);
            JOptionPane.showMessageDialog(this, "Data pasien dengan nama "+nama+" dan id pasien "+id+" telah terupdate");
            this.setVisible(false);
        }
         else{
             JOptionPane.showMessageDialog(this,"Silahkan Isi Status Terlebih Dahulu");
         }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
            
        }
    }//GEN-LAST:event_jLabelUpdateStatusMouseClicked

    private void jLabelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanDataPasien().setVisible(true);
    }//GEN-LAST:event_jLabelBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUpdateStatusKesehatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUpdateStatusKesehatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUpdateStatusKesehatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUpdateStatusKesehatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUpdateStatusKesehatan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1status;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelUpdateStatus;
    private javax.swing.JRadioButton jRadioButtonUpdateODP;
    private javax.swing.JRadioButton jRadioButtonUpdateOTG;
    private javax.swing.JRadioButton jRadioButtonUpdatePDP;
    private javax.swing.JRadioButton jRadioButtonUpdatePositif;
    private javax.swing.JRadioButton jRadioButtonUpdateSuspect;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldNamaIDPasien;
    private javax.swing.JTextField jTextFieldTindakanPerawatan;
    // End of variables declaration//GEN-END:variables
}
