/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database;

/**
 *
 * @author AMRI
 */
public class HalamanDisclaimer extends javax.swing.JFrame {

    /**
     * Creates new form HalamanDisclaimer
     */
    public HalamanDisclaimer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTombolHome = new javax.swing.JLabel();
        jLabelContactUs = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTombolHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/TombolHome.png"))); // NOI18N
        jLabelTombolHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTombolHomeMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelTombolHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 440, 80, 70));

        jLabelContactUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/TombolContactUs.png"))); // NOI18N
        jLabelContactUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelContactUsMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelContactUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 130, 40));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/HalamanDisclaimer.PNG"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelTombolHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTombolHomeMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanSetelahLogin().setVisible(true);
    }//GEN-LAST:event_jLabelTombolHomeMouseClicked

    private void jLabelContactUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelContactUsMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanHubungiKamii().setVisible(true);
    }//GEN-LAST:event_jLabelContactUsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanDisclaimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanDisclaimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanDisclaimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanDisclaimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanDisclaimer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelContactUs;
    private javax.swing.JLabel jLabelTombolHome;
    // End of variables declaration//GEN-END:variables
}
