/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AMRI
 */
public class HalamanDataCenter extends javax.swing.JFrame {
koneksi kon;
    /**
     * Creates new form HalamanDataCenter
     */
    public HalamanDataCenter() {
        kon = new koneksi();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRefresh = new javax.swing.JLabel();
        jLabelUpdate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelTombolHome = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/TombolRefresh.png"))); // NOI18N
        jLabelRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRefreshMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, 50));

        jLabelUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/TombolUpdateData.png"))); // NOI18N
        jLabelUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUpdateMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 170, 40));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 550, 170));

        jLabelTombolHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/TombolHome.png"))); // NOI18N
        jLabelTombolHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTombolHomeMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelTombolHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 80));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/halaman data center.PNG"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelTombolHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTombolHomeMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanSetelahLogin().setVisible(true);
    }//GEN-LAST:event_jLabelTombolHomeMouseClicked

    private void jLabelRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRefreshMouseClicked
        // TODO add your handling code here:
        Object header[]={"Positif","Orang Dalam Pemantauan","Pasien Dalam Pemantauan","Orang Tanpa Gejala","Suspect"};
        DefaultTableModel data= new DefaultTableModel(null, header);
        jTable1.setModel(data);
        String tampil = "select * from tb_jumlahpasien";
        try{
            Statement st=kon.con.createStatement();
            ResultSet rs=st.executeQuery(tampil);
            while(rs.next()){
                String kolom1 = rs.getString(1);
                String kolom2 = rs.getString(2);
                String kolom3 = rs.getString(3);
                String kolom4 = rs.getString(4);
                String kolom5 = rs.getString(5);
                String kolom[] = {kolom1,kolom2,kolom3,kolom4,kolom5};
                data.addRow(kolom);}
            }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "error"+e.getMessage());
        }
    }//GEN-LAST:event_jLabelRefreshMouseClicked

    private void jLabelUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUpdateMouseClicked
        // TODO add your handling code here:
        new HalamanUpdateDataCenter().setVisible(true);
    }//GEN-LAST:event_jLabelUpdateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanDataCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanDataCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanDataCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanDataCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanDataCenter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelRefresh;
    private javax.swing.JLabel jLabelTombolHome;
    private javax.swing.JLabel jLabelUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
