/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AMRI
 */
public class HalamanDataPasien extends javax.swing.JFrame {
    koneksi kon;

    /**
     * Creates new form HalamanDataPasien
     */
    public HalamanDataPasien() {
        kon = new koneksi();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1datapasien = new javax.swing.JTable();
        jTextField1CariData = new javax.swing.JTextField();
        jLabel1CariData = new javax.swing.JLabel();
        jLabelTambahPasien = new javax.swing.JLabel();
        jLabelUpdateStatus = new javax.swing.JLabel();
        jLabelHapusPasien = new javax.swing.JLabel();
        jLabelUpdateStatus1 = new javax.swing.JLabel();
        jLabelTombolHome = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1datapasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1datapasien);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 710, 270));
        getContentPane().add(jTextField1CariData, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 370, 70));

        jLabel1CariData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/caridata(1).png"))); // NOI18N
        jLabel1CariData.setText("jLabel1");
        jLabel1CariData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1CariDataMouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1CariData, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 160, 60));

        jLabelTambahPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/button_tambah(1).png"))); // NOI18N
        jLabelTambahPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTambahPasienMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelTambahPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, 170, 50));

        jLabelUpdateStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/updatestatus(1).png"))); // NOI18N
        jLabelUpdateStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUpdateStatusMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelUpdateStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 170, 50));

        jLabelHapusPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/button_hapus(1).png"))); // NOI18N
        jLabelHapusPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHapusPasienMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelHapusPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, 170, 50));

        jLabelUpdateStatus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/tamplkan(1).png"))); // NOI18N
        jLabelUpdateStatus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUpdateStatus1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelUpdateStatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 170, 50));

        jLabelTombolHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/TombolHome.png"))); // NOI18N
        jLabelTombolHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTombolHomeMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelTombolHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 430, 90, 70));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/HalamanPemantauanKesehatan.png"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelHapusPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHapusPasienMouseClicked
        // TODO add your handling code here:
        new FormHapusPasien().setVisible(true);
    }//GEN-LAST:event_jLabelHapusPasienMouseClicked

    private void jLabelTambahPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTambahPasienMouseClicked
        // TODO add your handling code here:
        new HalamanTambahPasien().setVisible(true);
    }//GEN-LAST:event_jLabelTambahPasienMouseClicked

    private void jLabelUpdateStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUpdateStatusMouseClicked
        // TODO add your handling code here:
        new FormUpdateStatusKesehatan().setVisible(true);
    }//GEN-LAST:event_jLabelUpdateStatusMouseClicked

    private void jLabelUpdateStatus1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUpdateStatus1MouseClicked
        // TODO add your handling code here:
        Object header[]={"Id Pasien","Nama Pasien","Alamat Pasien","No Handphone","Jenis Kelamin","Status Pasien","Tindakan"};
        DefaultTableModel data= new DefaultTableModel(null, header);
        jTable1datapasien.setModel(data);
        String tampil = "select * from tb_pasien";
        try{
            Statement st=kon.con.createStatement();
            ResultSet rs=st.executeQuery(tampil);
            while(rs.next()){
                String kolom1 = rs.getString(1);
                String kolom2 = rs.getString(2);
                String kolom3 = rs.getString(3);
                String kolom4 = rs.getString(4);
                String kolom5 = rs.getString(5);
                String kolom6 = rs.getString(6);
                String kolom7 = rs.getString(7);
                String kolom[] = {kolom1, kolom2, kolom3, kolom4, kolom5, kolom6, kolom7};
                data.addRow(kolom);}
            }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "error"+e.getMessage());
        }
        
    }//GEN-LAST:event_jLabelUpdateStatus1MouseClicked

    private void jLabelTombolHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTombolHomeMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanSetelahLogin().setVisible(true);
    }//GEN-LAST:event_jLabelTombolHomeMouseClicked

    private void jLabel1CariDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1CariDataMouseClicked
        // TODO add your handling code here:
        String cari;
        cari = jTextField1CariData.getText();
        Object header[]={"Id Pasien","Nama Pasien","Alamat Pasien","No Handphone","Jenis Kelamin","Status Pasien"};
        DefaultTableModel data= new DefaultTableModel(null, header);
        jTable1datapasien.setModel(data);
        String tampil = "select * from tb_pasien where nama like '%"+cari+"%'";
        try{
            Statement st=kon.con.createStatement();
            ResultSet rs=st.executeQuery(tampil);
            while(rs.next()){
               String kolom1 = rs.getString(1);
                String kolom2 = rs.getString(2);
                String kolom3 = rs.getString(3);
                String kolom4 = rs.getString(4);
                String kolom5 = rs.getString(5);
                String kolom6 = rs.getString(6);
                String kolom[] = {kolom1, kolom2, kolom3, kolom4, kolom5, kolom6};
                data.addRow(kolom);}
            }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "error"+e.getMessage());
        }
    }//GEN-LAST:event_jLabel1CariDataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanDataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanDataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanDataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanDataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanDataPasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1CariData;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelHapusPasien;
    private javax.swing.JLabel jLabelTambahPasien;
    private javax.swing.JLabel jLabelTombolHome;
    private javax.swing.JLabel jLabelUpdateStatus;
    private javax.swing.JLabel jLabelUpdateStatus1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1datapasien;
    private javax.swing.JTextField jTextField1CariData;
    // End of variables declaration//GEN-END:variables
}
