/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package database;

import javax.swing.JOptionPane;

/**
 *
 * @author AMRI
 */
public class HalamanSetelahLogin extends javax.swing.JFrame {

    /** Creates new form HalamanSetelahLogin */
    public HalamanSetelahLogin() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTombolInformation = new javax.swing.JLabel();
        jLabelTombolLogout = new javax.swing.JLabel();
        jLabelHalamanPemantauanPasien = new javax.swing.JLabel();
        jLabelHalamanDataCenter = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTombolInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/TombolInformation.png"))); // NOI18N
        jLabelTombolInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTombolInformationMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelTombolInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 440, 80, 60));

        jLabelTombolLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/TombolLogout.png"))); // NOI18N
        jLabelTombolLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTombolLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelTombolLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 120, 40));

        jLabelHalamanPemantauanPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/TombolDataPasien.png"))); // NOI18N
        jLabelHalamanPemantauanPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHalamanPemantauanPasienMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelHalamanPemantauanPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 120, 50));

        jLabelHalamanDataCenter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/TombolDataCenter.png"))); // NOI18N
        jLabelHalamanDataCenter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHalamanDataCenterMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelHalamanDataCenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 130, 50));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/HalamanSetelahLogin.PNG"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelTombolInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTombolInformationMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanTentang1().setVisible(true);
    }//GEN-LAST:event_jLabelTombolInformationMouseClicked

    private void jLabelHalamanPemantauanPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHalamanPemantauanPasienMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanDataPasien().setVisible(true);
    }//GEN-LAST:event_jLabelHalamanPemantauanPasienMouseClicked

    private void jLabelHalamanDataCenterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHalamanDataCenterMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanDataCenter().setVisible(true);
    }//GEN-LAST:event_jLabelHalamanDataCenterMouseClicked

    private void jLabelTombolLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTombolLogoutMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanHome().setVisible(true);                                          
    }//GEN-LAST:event_jLabelTombolLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanSetelahLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanSetelahLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanSetelahLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanSetelahLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanSetelahLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelHalamanDataCenter;
    private javax.swing.JLabel jLabelHalamanPemantauanPasien;
    private javax.swing.JLabel jLabelTombolInformation;
    private javax.swing.JLabel jLabelTombolLogout;
    // End of variables declaration//GEN-END:variables

}
